---
lister.new:
    - <Control>n
lister.newInSubfolders:
    - <Control><Shift>n
lister.execute:
    - Return
lister.parent:
    - <Control>p
lister.back:
    - <Alt>b
lister.forward:
    - <Alt>f
lister.openTerminalHere:
    - <Control>t
lister.showNavigationStack:
    - <Alt>n
lister.delete:
    - <Alt>d
lister.refresh:
    - <Control>r
lister.showListers:
    - <Control>l
lister.flipSourceAndDestination:
    - <Control>f
lister.info:
    - <Control>i
